apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: civicpulse
resources:
  - ../../base
images:
  - name: ghcr.io/khaliqtaimoor6-codes/civicpulse-backend
    newName: ghcr.io/khaliqtaimoor6-codes/civicpulse-backend
    newTag: sha-PLACEHOLDER
  - name: ghcr.io/khaliqtaimoor6-codes/civicpulse-frontend
    newName: ghcr.io/khaliqtaimoor6-codes/civicpulse-frontend
    newTag: sha-PLACEHOLDER
