apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: civicpulse
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: civicpulse-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: civicpulse-backend:ci
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: civicpulse-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: civicpulse-frontend:ci
