apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: civicpulse
  namespace: civicpulse
spec:
  ingressClassName: nginx
  rules:
    - host: civicpulse.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: civicpulse-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: civicpulse-frontend
                port:
                  number: 80
